spring:
  data:
    mongodb:
      username: adrien
      password: adrien
      additional-hosts: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090